### ISSUE TITLE
trim inputs

### ISSUE THREAD

**Issue by Dutchy-** [schollz/find#109]
I noticed that inputs from the android app are not trimmed before use.
I have a keyboard which tends to add spaces after a word when using completion, so I added a group "Home ". Consequently I had to use `/location?group=home%20` to access my data. I understand how that works, but i recommend trimming input.

**Comment by Dutchy-** [comment]
I also suspect some unexpected errors where some parts (e.g. the dashboard) do trim, so it thinks it has no data? I'm not sure, but should be fairly easy to reproduce.

**Comment by schollz** [comment]
Thanks, I'll look into this.

**Comment by Dutchy-** [comment]
Thanks!

**Comment by schollz** [comment]
@Dutchy- 

If you are using the public server and you need to migrate/rename your DB, let me know at zack@hypercubeplatforms.com. I still haven't implemented a route for automated migration, but its in the works! :)

**Comment by Dutchy-** [comment]
No I'm good, I use my own server :)
