### ISSUE TITLE
How to open the exported .db file ?

### ISSUE THREAD

**Issue by ckybonist** [schollz/find#117]
I exported my fingerprint data from dashboard (ml.internalpositioning.com/dashboard/...), while don't know how to open it.

Could anyone tell me which database program is suitable for opening this *.db file.

**Comment by schollz** [comment]
Its a BoltDB database file, which can be inspected using the [boltd tool](https://github.com/boltdb/boltd).

Alternatively, you can use FIND to dump the learning and tracking fingerprints directly as JSON. If your file is called `MYSTUFF.db` then use:

```find -dump MYSTUFF -data /path/to/MYSTUFF.db```

This will create a directory called `dump-MYSTUFF` with two files containing all the learning and tracking fingerprints. I realize this is a little clunky, but no one has used this feature to my knowledge (except me) and I'd be happy to improve it!

**Comment by ckybonist** [comment]
Thank you, I'll try it later 👍
