### ISSUE TITLE
This is an issue with the website

### ISSUE THREAD

**Issue by kdschlosser** [schollz/find#127]
On my mobile device the nag popup about getting updates for FIND cannot be closed. The popups close button is always just under the menu bar. You can see if when you scroll but can't click it,

Little bit frustrating when you want to learn about a product to be hit with something asking for your e-mail that you can't close and blocks what you are trying to read..

**Comment by schollz** [comment]
Got it! https://github.com/schollz/find/commit/851cc9fc47d29c760f80ad43c36155abb7cbe487
