### ISSUE TITLE
Can FIND work with multiple access points with the same name?

### ISSUE THREAD

**Issue by nikhiljangam** [schollz/find#136]
HI
   Its a great idea to locate internal positioning of user.But the doubt is that it works for multiple access points with same name in different locations in a college..

**Comment by schollz** [comment]
It works for different locations in a college. Access points (APs) can have the same name (or SSID), but each AP has a unique MAC address which is builtin to the hardware and cannot be changed. The MAC address is what FIND uses, not the SSID.

**Comment by nikhiljangam** [comment]
hmm...thanks very good work indeed..this can be applied to varied applications.I am also planning to do final project on this
