### ISSUE TITLE
Server stops publishing MQTT messages after around an hour

### ISSUE THREAD

**Issue by lwis** [schollz/find#144]
I'm using a custom MQTT broker with the docker image, and I don't see any errors in the logs - it just stops publishing to the broker after some time, only fixed by a restart. Logs show that it's still active and processing fingerprints.

**Comment by schollz** [comment]
That is strange. I wonder if it is related to https://github.com/schollz/find/issues/142, but I don't know why you don't see a panic in the log.

**Comment by tavalin** [comment]
I had something similar when I had network issues. I was wondering if the mqtt client tried to reconnect to the broker if the connection dropped.

**Comment by lwis** [comment]
@schollz I just double checked, I'm not seeing anything other than `POST    /track`, and `fingerprint.go:229` debug logs.

I can deploy changes/try anything to help debug.

@tavalin I think it's unlikely as my mqtt broker is hosted on the same box as FIND.

**Comment by lwis** [comment]
@schollz update;

I see `Socket error on client RylwF, disconnecting.` from mosquitto when the connection stops - I've also noticed that FIND subscribes to # - why is this?

**Comment by schollz** [comment]
FIND subscribes to # so any published fingerprint can be processed - see https://www.internalpositioning.com/server/#mqtt-support. Since MQTT is non-anonymous, it requires people to have passwords to subscribe/post. Instead of subscribing to each individual channel for each user/group, FIND just uses admin privileges to subscribe to all of them at once and delineate which ones its listening to when the fingerprint comes in.

I'm still puzzled by this error. Are you using a different MQTT broker than mosquito?

**Comment by lwis** [comment]
@schollz I'm using mosquitto, and FIND is subscribing to # on a busy broker, so it's receiving a high volume of messages it isn't interested in.

**Comment by tavalin** [comment]
Instead of subscribing to everything, Find could subscribe to the following topics:

```
+/location/+
+/track/+
+/learn/+
```

**Comment by lwis** [comment]
@tavalin that would improve things dramatically

**Comment by lwis** [comment]
Closing this for now as clearing my data appeared to fix it, not sure what could have caused it, though.

**Comment by lwis** [comment]
Actually, maybe just a red herring :(

**Comment by schollz** [comment]
I like @tavalin's fix - I will try to implement that when I get a chance.

@lwis do you see any logs about the issue? Could you try the non-docker version?

**Comment by lwis** [comment]
@schollz nothing abnormal in the logs, just debug lines from `fingerprint.go`.

Can do.
