### ISSUE TITLE
Docker automated build not up to date

### ISSUE THREAD

**Issue by chauffer** [schollz/find#162]
Seems it's not updated on every push as it should.
@schollz can you go to https://hub.docker.com/r/schollz/find/~/settings/automated-builds/ - tick this box, and trigger a build? ![](https://simone.sh/images/1492708901_HAqyBcSzPqLI.png)

Thanks!

**Comment by schollz** [comment]
Its already ticked, so I don't know why it wasn't triggering. I just triggered one manually.
