### ISSUE TITLE
MQTT issues

### ISSUE THREAD

**Issue by bastshoes** [schollz/find#178]
Hello. 
I'm using public server. MQTT server is not functioning properly. Connecting to your MQTT broker with mosquitto client I see that my device publishing fingirprints but internalpositioning server do not respond with location. My last location was updated on 9th of September.

**Comment by schollz** [comment]
Can you try it again? I just restarted mosquitto.

**Comment by bastshoes** [comment]
Thanks, now it's working.

**Comment by bastshoes** [comment]
Thanks, now it's working.

**Comment by bastshoes** [comment]
Hello @schollz.
MQTT server again lost connection to FIND server.

**Comment by schollz** [comment]
Thanks, should be working now
