### ISSUE TITLE
NO FINGERPRINTS FOUND TO INSERT, SEE API

### ISSUE THREAD

**Issue by tushe** [schollz/find#194]
I tried to compile and install it on my phone and I got that error when I tried to send fingerprint...

**Comment by schollz** [comment]
Can you verify that your WiFi is enabled? Also, are their any WiFi APs in
your vicinity?

**Comment by tushe** [comment]
Hi @schollz I've WIFI enabled and I've a WiFi APs in my vicinity, with the play store version it works, with my compiled version it doesn't work :(

**Comment by schollz** [comment]
The compiled app doesn't work? Which repo did you compile?

**Comment by tushe** [comment]
This repo with cordova

**Comment by tushe** [comment]
I added the plug-in and i compiled it, I installed the apk on my smartphone but it can't send fingerprints...

**Comment by schollz** [comment]
Hm. There are a couple things, could you setup a local server and see if
it's connecting at all? I think most likely it's a Android permissions
issue. The Google Play app seems to be grandfathered into the old
permissions scheme, but they changed it on next Android versions where the
app needs to explicitly request permissions.

**Comment by tushe** [comment]
Ok, I was setup a local server but the result was the same. 
If I'll have time I could develop a new version of this Cordova based app and i'll share it. 
Thank you for your help.

**Comment by schollz** [comment]
You might check out https://github.com/uncleashi/find-client-android, it
works well too, and is more up to date.

**Comment by tushe** [comment]
Thanks, I compiled that native app and tested it, but seem it has some issue about determining the position.

**Comment by ishanjain28** [comment]
@schollz I am having this same problem on Find's Android Application. The server is https://ml.internalpositioning.com.

**Comment by schollz** [comment]
Did you do learning? Could you send me your group name?

**Comment by tushe** [comment]
I solved my issue with compiled cordova app just adding this in AndroidManifest.xml:

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

After installing go to Settings -> Applications -> Find -> Authorization  and enable Position.

**Comment by ishanjain28** [comment]
@schollz I did learning/tracking both were giving same error. Then I tried running `findclient` from my PC and that worked just fine. 

My group name is "ishanjain28group"

**Comment by tushe** [comment]
I solved the issue with my cordova compiled application, just added the permission on AndroidManifest.xml

uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"

On Android on app authorization enable position.

**Comment by tushe** [comment]
It would be nice to have a dialog box to enable the authorization.
It could be the solution:
https://github.com/dpa99c/cordova-diagnostic-plugin

or modify the WiFi plugin:
https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#android-permissions

**Comment by tushe** [comment]
It would be nice to have a dialog box to enable the authorization.
They could be the solution:
1) Add this functionality: https://github.com/dpa99c/cordova-diagnostic-plugin
2) Modify wifi plugin: https://cordova.apache.org/docs/en/latest/guide/platforms/android/plugin.html#android-permissions
