### ISSUE TITLE
can't build/compile

### ISSUE THREAD

**Issue by 9H1LO** [schollz/find#199]
Ubuntu 16 on x86

git clone https://github.com/schollz/find.git
cd find
go get ./...

package context: unrecognized import path "context"
Username for 'https://github.com':
Password for 'https://github.com':
# cd .; git clone https://github.com/foo/vendored /root/find/src/github.com/foo/vendored
Cloning into '/root/find/src/github.com/foo/vendored'...
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/foo/vendored/'
package github.com/thinkerou/favicon
        imports golang.org/x/sync/errgroup
        imports github.com/foo/vendored: exit status 128

is there some ready x86 binaries available or better documentation or an install method (apt?) not using "GO" as have no idea of it

**Comment by schollz** [comment]
Sorry! You don't need `go get ./...` anymore because all the libraries are vendored. But to use the vendored libraries you have to work in the GOPATH. I will update the documentation, but here is how you should build:

```
go get github.com/schollz/find
cd $GOPATH/src/github.com/schollz/find
go build
```

**Comment by 9H1LO** [comment]
wow ! quick reply ! thanks i'll try that

**Comment by 9H1LO** [comment]
what should $GOPATH be set to ?

root@haserver:~# cd find
root@haserver:~/find# go get github.com/schollz/find
package github.com/schollz/find: cannot download, $GOPATH not set. For more details see: go help gopath

**Comment by schollz** [comment]
See https://golang.org/doc/code.html#GOPATH

Also, maybe download the latest version of Go, as it will do it automatically

**Comment by 9H1LO** [comment]
root@haserver:~/go/src/github.com/schollz/find# export GOPATH="/root/go"

root@haserver:~/go/src/github.com/schollz/find# cd $GOPATH/src/github.com/schollz/find

root@haserver:~/go/src/github.com/schollz/find# go build
../../boltdb/bolt/bolt_unix_solaris.go:10:2: cannot find package "golang.org/x/sys/unix" in any of:
        /usr/lib/go/src/pkg/golang.org/x/sys/unix (from $GOROOT)
        /root/go/src/golang.org/x/sys/unix (from $GOPATH)

**Comment by schollz** [comment]
Did you install Go with `apt-get`? 

I'd suggest just downloading it - its easier: https://golang.org/doc/install#tarball

**Comment by 9H1LO** [comment]
thanks schollz !

yes as a note to all others, GO was installed via apt and it didn't work for me

i downloaded and extracted the tarball and its running fine now

managed to build and run find 

thanks again and all the best

**Comment by schollz** [comment]
Great! Let me know if you have more questions.
