### ISSUE TITLE
Redo /whereami route for GIS server

### ISSUE THREAD

**Issue by schollz** [schollz/find#20]

**Comment by sjsafranek** [comment]
{
 username: [location_name]
}

**Comment by sjsafranek** [comment]
{
   username: [
      Location_name: {
         <machine learning properties>
      }
   ]
}

First item in the array of locations in the last location for that user

**Comment by schollz** [comment]
`/location?group=GROUP&history=X&user=USER`

`history` and `user` are optional. `history` defaults to 1. `user` defaults to all users.

```json
{
    "user": [
        {
            "time": "2016-04-16 08:16:43.123233725 -0400 EDT",
            "location": "",
            "bayes": {}
        }
    ]
}
```

**Comment by schollz** [comment]
https://github.com/schollz/find/commit/89d389a93ca8fb78c22ea761a692f5400f3c5f5b

/location?group=GROUP&user=user1
/location?group=GROUP&users=user1,user2
