### ISSUE TITLE
What about precision range?

### ISSUE THREAD

**Issue by coumarc9** [schollz/find#216]
Hi,

I’m maybe planning to install this project. I would like to know what’s the precision range with a good configuration and training (with or without app, with or without Pi cluster). Is it about 1-3-5-10 meters?

Thank you,

**Comment by schollz** [comment]
It really depends on the surrounding APs if you do active scanning, or the number of Pis in your cluster for passive scanning. I can generally get 10 square meters (basically room level, and subroom level for really big rooms).
