### ISSUE TITLE
had to 'pip install apscheduler'

### ISSUE THREAD

**Issue by kootenpv** [schollz/find#3]
I had to run pip install specifically on "apscheduler" to get it to work. Surprisingly I don't think there was a bug when installing.

Using Python 3.5 on a Mac

Not sure if possible, but perhaps it would work to change  `APScheduler` -> `apscheduler` here:

https://github.com/schollz/find/blob/master/setup.py#L10

**Comment by schollz** [comment]
Thanks, I've fixed that.
