### ISSUE TITLE
livestats "socket.gethostbyname(socket.gethostname())" errors on pyhon server.py

### ISSUE THREAD

**Issue by kootenpv** [schollz/find#4]
I guess I did something to my computer to make this not work, but perhaps there is a way for you to change this somehow:

socket.gethostname() == 'MBP' # True

\>> socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

At the moment I just hardcoded it to `127.0.0.1` instead.

**Comment by schollz** [comment]
Thanks. I'm not sure why it didn't work for you, but I've caught the error now
