### ISSUE TITLE
how to integrate

### ISSUE THREAD

**Issue by sander76** [schollz/find#66]
Just ran into this. Looks absolutely amazing !
But I can't find anything in the info on how to integrate with other systems
like homeassistant.io or mqtt .
Can you give some pointers ?

**Comment by EliasGabrielsson** [comment]
The best document I found so far is this: 
https://github.com/schollz/find/blob/docs/docs/index.md

**Comment by sander76** [comment]
thanks ! That was what I was looking for....

**Comment by schollz** [comment]
I've never seen homeassistant.io - it looks really cool. 

The API is mostly frozen. For your purposes you likely need to poll [`/location`](https://github.com/schollz/find/blob/docs/docs/index.md#get-locationgroupxusery-or-locationgroupx-or-locationgroupxuseryzw) with a Python script and do what you want with the response. 

Please let me know if you make a little homeassistant script, itd be great to share! Also, please let me know if you need some functionality that’s not currently present on the API and I can build it in.

**Comment by sander76** [comment]
@schollz 
I posted about Find on the homeassistant forum:
Seemed at least one person already knew about it ;-)

https://community.home-assistant.io/t/anyone-seen-this-find-internal-positioning/772

**Comment by schollz** [comment]
Oh awesome! Except that route doesn't exist now lol. Its been replaced by simply `/location?group=X`

**Comment by EliasGabrielsson** [comment]
@schollz 
FYI: There is an ongoing thread for openHAB how to utilize this framework as well.
https://community.openhab.org/t/find-high-precision-indoor-positioning-framework-for-most-wifi-enabled-devices/9909/8

**Comment by schollz** [comment]
@EliasGabrielsson Thanks, I've updated their conversations with the new API as well. Sorry for confusing everyone ;)

**Comment by EliasGabrielsson** [comment]
No worries, thats the nature of open source development.
Thx for the work you done, I am really impressed by the quality of the classification.
