### ISSUE TITLE
Dashboard not showing tracking information if username is an email.

### ISSUE THREAD

**Issue by pablomusumeci** [schollz/find#81]
This is the message I see in Chrome's console.

jquery-2.0.0.min.js:4 Uncaught Error: Syntax error, unrecognized expression: #lastSeenpablo.musumeci@mulesoft.com

I think that the problem is caused by the dot in the email. Not sure if the @ has something to do with the error.

**Comment by schollz** [comment]
Thanks, this is a jQuery issue. I just pushed a fix for usernames. It might still exist for group names.. Try it and let me know.

https://github.com/schollz/find/commit/2a5d9d58acae052fed5e57f83f273989d582998b
