### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by wutu** [schollz/find#82]
Great software, you plan to support MQTT? It would certainly facilitated the integration with multiple systems.

**Comment by schollz** [comment]
Yes, I think this would be a great addition. I don't know much about it. I'll open this up as a feature request for others to help with!

Seems like there are some Golang packages to get started with: https://github.com/yosssi/gmq

**Comment by schollz** [comment]
Okay, it was a lot easier then I thought! I added it already. Its not live yet as I'm not sure what kind of info you'd like. Should I just pass the JSON of the current location data through the MQTT messages?

**Comment by wutu** [comment]
superfast, thx.

**Comment by tavalin** [comment]
Is it possible to specify a private MQTT server?

**Comment by schollz** [comment]
I've now realized that MQTT is in no way private by default lol. I'm taking it offline for now.

I think a "okay" solution will be to allow users to specifically request a MQTT connection, at which I will add their Group to a ACL file that allows access. Of course, still anyone can access this, but this is the general scheme of how FIND currently works (security through obfuscation). The main thing here is that I need to disallow the wildcard rooms so that people can't spectate all the transactions...

I'm open to other suggestions too!

**Comment by schollz** [comment]
Okay I found a way to do this, its going to be limited to Linux systems for now.

**Comment by schollz** [comment]
Okay, sorry, I have a "secure" MQTT now (https://github.com/schollz/find/commit/d34af10964bf48619d6fd674ebee676ca1ecf9a8). Basically you have to subscribe to have MQTT access, and then you can authenticate yourself in the MQTT channel so others can't snoop.

[Read this to get started](https://github.com/schollz/find/blob/docs/docs/mqtt.md) and let me know if you have questions!

**Comment by tavalin** [comment]
@schollz Did you have any comments on allowing users to specify the mqtt server?

**Comment by schollz** [comment]
@tavalin Do you mean, allowing users to specify a different mqtt server that you can listen to the locations determined from FIND? I.e. having FIND forward the messages to a different MQTT server? This doesn't exist, but I can add it if you need that.

**Comment by tavalin** [comment]
Yes. As I'm running my own Find server I'd also like Find to forward the location info to my own MQTT server too (rather than have my data in the cloud).

**Comment by schollz** [comment]
Okay, that you can do. [Here are the instructions](https://github.com/schollz/find/blob/docs/docs/mqtt.md). Right now its only setup for mosquitto. Let me know if you have problems.
