### ISSUE TITLE
Get Mosquitto PID automatically, since I forget to reset it when resetting server

### ISSUE THREAD

**Issue by schollz** [schollz/find#94]

**Comment by johnjore** [comment]
Until fixed replace the PID with `pgrep mosquitto`. Added to OpenHAB wiki.

**Comment by schollz** [comment]
Thanks, that's a nice solution. I've added it.

**Comment by schollz** [comment]
Since gettings process IDs varies in different systems, I'm going to leave this as the main solution. I've updated the [docs](https://doc.internalpositioning.com/mqtt/#setup-self-hosted-servers) to reflect this.
