### ISSUE TITLE
SVM - Not Detected

### ISSUE THREAD

**Issue by johnjore** [schollz/find#98]
Hi!

I installed SVM by using the onscreen instructions that appear when find starts. 
1) If SVM binaries are copied to same folder as find, find still claims SVM is not found
2) If SVM binaries are moved to somewhere in path, /usr/local/bin, they are found
3) The `cp svm-xyz .. ` command is therefore a little missleading.
4) Instructions are a little out dated as they refer to 3.18, not 3.21 which is the current version. 

Maybe add a readme.txt file with some basic instructions?

**Comment by schollz** [comment]
Thanks, I added it to the [docs](https://doc.internalpositioning.com/svm/), changed the server message, and added line about it in the readme.

As a note, I've found SVM pretty inaccurate and slow (usually lags a fingerprint behind) compared to NB. Not sure why, maybe there's some optimizations I'm not aware of. I've already played around with the optimizations a bit and it improved it....SVM seems to need lots of fiddling.
